name: probs_design
channels:
- conda-forge
- pkgs/main
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=2.0.0
- bottleneck=1.3.5
- brotli=1.1.0
- brotli-bin=1.1.0
- ca-certificates=2024.6.2
- certifi=2024.6.2
- cycler=0.11.0
- debugpy=1.6.3
- decorator=5.1.1
- entrypoints=0.4
- fonttools=4.38.0
- freetype=2.12.1
- imbalanced-learn=0.8.1
- ipykernel=6.16.2
- ipython=7.33.0
- jedi=0.19.1
- joblib=0.17.0
- jpeg=9e
- jupyter_client=7.4.9
- jupyter_core=4.11.1
- kiwisolver=1.4.4
- lcms2=2.14
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libblas=3.9.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcblas=3.9.0
- libdeflate=1.14
- libffi=3.3
- libgcc-ng=13.2.0
- libgfortran-ng=13.2.0
- libgfortran5=13.2.0
- libgomp=13.2.0
- liblapack=3.9.0
- libopenblas=0.3.25
- libpng=1.6.43
- libsodium=1.0.18
- libsqlite=3.46.0
- libstdcxx-ng=13.2.0
- libtiff=4.4.0
- libwebp-base=1.4.0
- libxcb=1.13
- libzlib=1.2.13
- matplotlib-base=3.5.3
- matplotlib-inline=0.1.7
- munkres=1.1.4
- ncurses=6.5
- nest-asyncio=1.6.0
- nomkl=1.0
- numexpr=2.8.3
- numpy=1.21.6
- openjpeg=2.5.0
- openssl=1.1.1w
- packaging=23.2
- pandas=1.3.5
- parso=0.8.4
- patsy=0.5.6
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=9.2.0
- pip=24.0
- prompt-toolkit=3.0.47
- psutil=5.9.3
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pygments=2.17.2
- pyparsing=3.1.2
- python=3.7.8
- python-dateutil=2.9.0
- python_abi=3.7
- pytz=2024.1
- pyzmq=24.0.1
- readline=8.2
- scikit-learn=1.0.1
- scipy=1.7.3
- seaborn=0.9.0
- setuptools=69.0.3
- six=1.16.0
- sqlite=3.46.0
- statsmodels=0.13.2
- threadpoolctl=3.1.0
- tk=8.6.13
- tornado=6.2
- traitlets=5.9.0
- typing-extensions=4.7.1
- typing_extensions=4.7.1
- unicodedata2=14.0.0
- wcwidth=0.2.10
- wheel=0.42.0
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xz=5.2.6
- zeromq=4.3.5
- zlib=1.2.13
- zstd=1.5.6

